"""Test fixtures: a real HTTP server for the audio, and a canned pipeline for pyannote.

Nothing here imports torch. The whole point of the `Pipeline` protocol in `diarize.py` is
that the routes, the registry, the idempotency, the single slot and the cleanup can all be
tested without a 2 GB dependency and a gated model download — those are what the container
build and the contract test cover, and they are the wrong tool for asserting that a second
key gets a 429.

The audio *is* real: a 12-second WAV generated by ffmpeg and served over a genuine HTTP
server, because the failure modes being tested — an empty object, a duration mismatch, an
expired URL — are all about the fetch, and a monkeypatched `urlopen` would test the
monkeypatch.
"""

from __future__ import annotations

import subprocess
import threading
import time
from http.server import HTTPServer, SimpleHTTPRequestHandler
from pathlib import Path
from typing import Any, Callable, Iterator

import pytest


@pytest.fixture(scope="session")
def audio_dir(tmp_path_factory: pytest.TempPathFactory) -> Path:
    """A directory holding the served files: a 12 s tone, a 4 s tone, and an empty file."""
    directory = tmp_path_factory.mktemp("audio")
    for name, seconds in (("twelve.wav", 12), ("four.wav", 4)):
        subprocess.run(
            [
                "ffmpeg", "-v", "error", "-y",
                "-f", "lavfi", "-i", f"sine=frequency=220:duration={seconds}",
                "-ac", "1", "-ar", "16000",
                str(directory / name),
            ],
            check=True,
        )
    (directory / "empty.wav").write_bytes(b"")
    (directory / "garbage.wav").write_bytes(b"this is not audio" * 100)
    return directory


@pytest.fixture(scope="session")
def audio_server(audio_dir: Path) -> Iterator[str]:
    """Serve `audio_dir` on a real socket, and return the base URL."""

    class Handler(SimpleHTTPRequestHandler):
        def __init__(self, *args: Any, **kwargs: Any) -> None:
            super().__init__(*args, directory=str(audio_dir), **kwargs)

        def log_message(self, *_args: Any) -> None:  # keep the test output readable
            pass

    server = HTTPServer(("127.0.0.1", 0), Handler)
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    try:
        yield f"http://127.0.0.1:{server.server_port}"
    finally:
        server.shutdown()
        server.server_close()


class CannedPipeline:
    """A pyannote pipeline that returns known turns.

    Calls the hook the way pyannote does, so cancellation, the deadline and progress
    reporting are exercised by the same code path the real pipeline drives. `delay_s`
    spreads the hook calls out so a test can cancel something that is genuinely mid-run
    rather than racing a function that has already returned.
    """

    def __init__(
        self,
        turns: list[tuple[float, float, str]] | None = None,
        *,
        delay_s: float = 0.0,
        steps: int = 4,
        on_call: Callable[[], None] | None = None,
        wrap_output: bool = True,
    ) -> None:
        self.turns = turns if turns is not None else [(0.0, 4.0, "SPEAKER_00"), (4.5, 11.5, "SPEAKER_01")]
        self.delay_s = delay_s
        self.steps = steps
        self.on_call = on_call
        # pyannote 4.x wraps the Annotation in a DiarizeOutput dataclass; 3.x returns it
        # bare. Default to the 4.x shape because that is what the image installs, and keep
        # the bare one reachable so the duck-typing in `run_diarization` is covered both
        # ways. The first version of this fixture only produced the bare shape, and every
        # test passed against a shape the real model does not return.
        self.wrap_output = wrap_output
        self.calls = 0

    def to(self, _device: Any) -> "CannedPipeline":
        return self

    def __call__(self, _audio: str, hook: Callable[..., None] | None = None, **_kwargs: Any) -> Any:
        self.calls += 1
        if self.on_call:
            self.on_call()
        for step in range(self.steps):
            if hook:
                hook("segmentation", completed=step, total=self.steps)
            if self.delay_s:
                time.sleep(self.delay_s)
        if hook:
            hook("segmentation", completed=self.steps, total=self.steps)
        annotation = _Annotation(self.turns)
        return _DiarizeOutput(annotation) if self.wrap_output else annotation


class _DiarizeOutput:
    """pyannote 4.x's return shape: two Annotations plus embeddings.

    `exclusive_speaker_diarization` is deliberately given *different* turns — the
    overlap-free view — so a test would fail loudly if the code ever read the wrong field.
    """

    def __init__(self, annotation: "_Annotation") -> None:
        self.speaker_diarization = annotation
        self.exclusive_speaker_diarization = _Annotation([(0.0, 1.0, "WRONG_FIELD")])
        self.speaker_embeddings = None


class _Segment:
    def __init__(self, start: float, end: float) -> None:
        self.start = start
        self.end = end


class _Annotation:
    def __init__(self, turns: list[tuple[float, float, str]]) -> None:
        self._turns = turns

    def itertracks(self, yield_label: bool = False) -> Iterator[Any]:
        # Deliberately yielded out of order: `run_diarization` sorts, and a test that fed
        # it pre-sorted input would not be checking that.
        for start, end, label in reversed(self._turns):
            yield (_Segment(start, end), "_", label) if yield_label else (_Segment(start, end), "_")
